#! /bin/sh

[[ -f ~/.xprofile ]] && source ~/.xprofile &

# start the hotkey daemon
pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config honor_fullscreen true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating

picom --config ~/.config/picom/picom.conf &

dunst &
nm-applet &
volumeicom &

spotifyd --config-path ~/.config/spotifyd/spotifyd.conf

kitty &

feh --bg-fill /home/oarabilekoore/Pictures/Wallpapers/2.jpg

~/.config/polybar/launch.sh &